// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const HuntPoints = sequelize.define('hunt_points', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(hunt_points_id_seq::regclass)'),
    },
  }, {
    tableName: 'hunt_points',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  HuntPoints.associate = (models) => {
    HuntPoints.belongsTo(models.point_of_interests, {
      foreignKey: {
        name: 'pointOfInterestId',
        field: 'point_of_interest_id',
      },
      as: 'pointOfInterest',
    });
    HuntPoints.belongsTo(models.treasure_hunts, {
      foreignKey: {
        name: 'treasureHuntId',
        field: 'treasure_hunt_id',
      },
      as: 'treasureHunt',
    });
  };

  return HuntPoints;
};
