// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Routes = sequelize.define('routes', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(routes_id_seq::regclass)'),
    },
    title: {
      type: DataTypes.STRING,
    },
    description: {
      type: DataTypes.STRING,
    },
    shortDesc: {
      type: DataTypes.STRING,
    },
    type: {
      type: DataTypes.STRING,
    },
    zone: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    status: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'routes',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Routes.associate = (models) => {
    Routes.belongsTo(models.users, {
      foreignKey: {
        name: 'userId',
        field: 'user_id',
      },
      as: 'user',
    });
    Routes.belongsTo(models.cities, {
      foreignKey: {
        name: 'cityId',
        field: 'city_id',
      },
      as: 'city',
    });
  };

  return Routes;
};
