// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const RoutePoints = sequelize.define('route_points', {
    id: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(route_points_id_seq::regclass)'),
    },
  }, {
    tableName: 'route_points',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  RoutePoints.associate = (models) => {
    RoutePoints.belongsTo(models.routes, {
      foreignKey: {
        name: 'routeId',
        field: 'route_id',
      },
      as: 'route',
    });
    RoutePoints.belongsTo(models.point_of_interests, {
      foreignKey: {
        name: 'pointOfInterestId',
        field: 'point_of_interest_id',
      },
      as: 'pointOfInterest',
    });
  };

  return RoutePoints;
};
